# run cargo test & build in hostuff-rs/ at branch dev.
name: hotstuff-rs-cargo

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@dev
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./hotstuff-rs
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./hotstuff-rs
      run: cargo test --verbose
