# run cargo test & build in hostuff-rs/ at branch master.
name: hotstuff-rs-cargo

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./hs-test
      run: cargo build 
    - name: Run hotstuff tests
      working-directory: ./hs-test
      run: cargo test 
