# run cargo test & build in hostuff-rs/ at branch master.
name: hotstuff-rs-cargo

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: hotstuff_test_mocker
          MYSQL_ROOT_PASSWORD: helloworld
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - uses: actions/checkout@v1
    - name: Build hs-test
      working-directory: ./hs-test
      run: cargo build 
    - name: Test-Safety
      working-directory: ./hs-test
      run: cargo test safety
    
