# run cargo test & build in hostuff-rs/ at branch master.
name: hotstuff-rs-cargo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: ./hotstuff-rs
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./hotstuff-rs
      run: cargo test --verbose
